
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ActivityQuestType
    {
        /// <summary>
        /// 产生棋子
        /// </summary>
        CreateChess = 0,
        /// <summary>
        /// 完成订单
        /// </summary>
        CompleteOrder = 1,
        /// <summary>
        /// 花费钻石
        /// </summary>
        SpendGem = 2,
        /// <summary>
        /// 合并棋子
        /// </summary>
        MergeChess = 3,
    }

} 

