
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    [System.Flags]
    public enum ActivityPointGainType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 合成获得
        /// </summary>
        Merge = 1,
        /// <summary>
        /// 生产器产生棋子获得
        /// </summary>
        Producer = 2,
        /// <summary>
        /// 获得卡包
        /// </summary>
        CardBag = 3,
        /// <summary>
        /// 订单完成
        /// </summary>
        Order = 4,
        /// <summary>
        /// 花费钻石
        /// </summary>
        SpendGem = 8,
        /// <summary>
        /// 获得金币
        /// </summary>
        GainCoin = 16,
        /// <summary>
        /// 消耗体力
        /// </summary>
        CoumeEnergy = 32,
        /// <summary>
        /// 道具获得
        /// </summary>
        Prop = 64,
    }

} 

