
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ActivityType
    {
        /// <summary>
        /// 常规
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 订单
        /// </summary>
        Order = 1,
        /// <summary>
        /// 主要装饰
        /// </summary>
        MainDecor = 2,
    }

} 

