
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum BuilldRewardType
    {
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 周活
        /// </summary>
        WeekActivity = 1,
        /// <summary>
        /// 月活
        /// </summary>
        Event = 2,
        /// <summary>
        /// 通用
        /// </summary>
        Community = 3,
        /// <summary>
        /// 特殊
        /// </summary>
        Special = 4,
    }

} 

