
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum CardRare
    {
        /// <summary>
        /// 绿色
        /// </summary>
        Green = 0,
        Blue = 1,
        Purple = 2,
        Orange = 3,
        Color = 4,
    }

} 

