
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Chess_Config
{
    private readonly System.Collections.Generic.Dictionary<int, Chess_ConfigItem> _dataMap;
    private readonly System.Collections.Generic.List<Chess_ConfigItem> _dataList;
    
    public Chess_Config(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chess_ConfigItem>();
        _dataList = new System.Collections.Generic.List<Chess_ConfigItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chess_ConfigItem _v;
            _v = Chess_ConfigItem.DeserializeChess_ConfigItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chess_ConfigItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Chess_ConfigItem> DataList => _dataList;

    public Chess_ConfigItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chess_ConfigItem Get(int key) => _dataMap[key];
    public Chess_ConfigItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

