
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ChessGuideType
    {
        /// <summary>
        /// 生成特定棋子
        /// </summary>
        SpawnSpecific = 0,
        /// <summary>
        /// 生成特定组棋子
        /// </summary>
        SpawnGroup = 1,
        /// <summary>
        /// 生成特定类型棋子
        /// </summary>
        SpawnType = 2,
    }

} 

