
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Chess_InitialItem : Luban.BeanBase
{
    public Chess_InitialItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ChessId = _buf.ReadInt();
        State = _buf.ReadInt();
    }

    public static Chess_InitialItem DeserializeChess_InitialItem(ByteBuf _buf)
    {
        return new Chess_InitialItem(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 默认棋子id
    /// </summary>
    public readonly int ChessId;
    /// <summary>
    /// 状态-1锁住,0半解锁，解锁
    /// </summary>
    public readonly int State;
   
    public const int __ID__ = 1452978552;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "chessId:" + ChessId + ","
        + "state:" + State + ","
        + "}";
    }
}

}

