
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Chess_Group
{
    private readonly System.Collections.Generic.Dictionary<int, Chess_GroupItem> _dataMap;
    private readonly System.Collections.Generic.List<Chess_GroupItem> _dataList;
    
    public Chess_Group(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chess_GroupItem>();
        _dataList = new System.Collections.Generic.List<Chess_GroupItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chess_GroupItem _v;
            _v = Chess_GroupItem.DeserializeChess_GroupItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chess_GroupItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Chess_GroupItem> DataList => _dataList;

    public Chess_GroupItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chess_GroupItem Get(int key) => _dataMap[key];
    public Chess_GroupItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

