
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Chess_TagItem : Luban.BeanBase
{
    public Chess_TagItem(ByteBuf _buf) 
    {
        Id = (ChessTagType)_buf.ReadInt();
        TagName = _buf.ReadString();
        Icon = _buf.ReadString();
    }

    public static Chess_TagItem DeserializeChess_TagItem(ByteBuf _buf)
    {
        return new Chess_TagItem(_buf);
    }

    /// <summary>
    /// groupID
    /// </summary>
    public readonly ChessTagType Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string TagName;
    /// <summary>
    /// 图片
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 903587662;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tagName:" + TagName + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

