
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ChessType
    {
        /// <summary>
        /// 商品
        /// </summary>
        Product = 0,
        /// <summary>
        /// 生产器-普通:生产消耗体力,库存用完后进入冷却以恢复库存
        /// </summary>
        NormalProducer = 1,
        /// <summary>
        /// 生产器-自动:生产不消耗体力,有空位则自动生产,库存用完后进入冷却以恢复库存
        /// </summary>
        AutoProducer = 2,
        /// <summary>
        /// 生产器-状态:切换状态消耗体力,切换特定状态生产棋子
        /// </summary>
        StateProducer = 3,
        /// <summary>
        /// 宝箱
        /// </summary>
        Treasure = 4,
        /// <summary>
        /// 其他:包括货币,剧情道具,以及后续新增的道具
        /// </summary>
        Currency = 5,
        /// <summary>
        /// 万能棋子
        /// </summary>
        AllPowerful = 6,
        /// <summary>
        /// 剧情棋子
        /// </summary>
        Task = 7,
        /// <summary>
        /// 气泡棋子
        /// </summary>
        Bubbly = 8,
        /// <summary>
        /// 活动棋子
        /// </summary>
        Activity = 9,
        /// <summary>
        /// 自选棋子
        /// </summary>
        SelectBox = 10,
        /// <summary>
        /// 订单宝箱棋子
        /// </summary>
        OrderBox = 11,
        /// <summary>
        /// 剪刀棋子
        /// </summary>
        Shear = 12,
        /// <summary>
        /// 需要被组合的棋子
        /// </summary>
        Combination = 13,
    }

} 

