
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Chess_TypeProperty
{
    private readonly System.Collections.Generic.Dictionary<ChessType, Chess_TypePropertyItem> _dataMap;
    private readonly System.Collections.Generic.List<Chess_TypePropertyItem> _dataList;
    
    public Chess_TypeProperty(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ChessType, Chess_TypePropertyItem>();
        _dataList = new System.Collections.Generic.List<Chess_TypePropertyItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chess_TypePropertyItem _v;
            _v = Chess_TypePropertyItem.DeserializeChess_TypePropertyItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Type, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ChessType, Chess_TypePropertyItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Chess_TypePropertyItem> DataList => _dataList;

    public Chess_TypePropertyItem GetOrDefault(ChessType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chess_TypePropertyItem Get(ChessType key) => _dataMap[key];
    public Chess_TypePropertyItem this[ChessType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

