
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ChessDetailType
    {
        /// <summary>
        /// 常规
        /// </summary>
        Nomal = 0,
        /// <summary>
        /// 宝箱提示
        /// </summary>
        Tip = 1,
        /// <summary>
        /// 数量加概率
        /// </summary>
        ContainRate = 2,
        /// <summary>
        /// 特殊生产器
        /// </summary>
        SpecialProducer = 3,
        /// <summary>
        /// 组合棋子
        /// </summary>
        Combination = 4,
    }

} 

