
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Chess_TypePropertyItem : Luban.BeanBase
{
    public Chess_TypePropertyItem(ByteBuf _buf) 
    {
        Type = (ChessType)_buf.ReadInt();
        NotMaxContentStr = _buf.ReadString();
        MaxContentStr = _buf.ReadString();
        ChessDetailTag = (ChessDetailTag)_buf.ReadInt();
    }

    public static Chess_TypePropertyItem DeserializeChess_TypePropertyItem(ByteBuf _buf)
    {
        return new Chess_TypePropertyItem(_buf);
    }

    /// <summary>
    /// 棋子类型
    /// </summary>
    public readonly ChessType Type;
    /// <summary>
    /// 非最大描述
    /// </summary>
    public readonly string NotMaxContentStr;
    /// <summary>
    /// 最大描述
    /// </summary>
    public readonly string MaxContentStr;
    /// <summary>
    /// 自带的标签，有特殊
    /// </summary>
    public readonly ChessDetailTag ChessDetailTag;
   
    public const int __ID__ = -1817967999;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "notMaxContentStr:" + NotMaxContentStr + ","
        + "maxContentStr:" + MaxContentStr + ","
        + "chessDetailTag:" + ChessDetailTag + ","
        + "}";
    }
}

}

