
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Chess_Tag
{
    private readonly System.Collections.Generic.Dictionary<ChessTagType, Chess_TagItem> _dataMap;
    private readonly System.Collections.Generic.List<Chess_TagItem> _dataList;
    
    public Chess_Tag(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ChessTagType, Chess_TagItem>();
        _dataList = new System.Collections.Generic.List<Chess_TagItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chess_TagItem _v;
            _v = Chess_TagItem.DeserializeChess_TagItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ChessTagType, Chess_TagItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Chess_TagItem> DataList => _dataList;

    public Chess_TagItem GetOrDefault(ChessTagType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chess_TagItem Get(ChessTagType key) => _dataMap[key];
    public Chess_TagItem this[ChessTagType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

