
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ChessTagType
    {
        /// <summary>
        /// 棋子
        /// </summary>
        Chess = 0,
        /// <summary>
        /// 生产器
        /// </summary>
        Producer = 1,
        /// <summary>
        /// 剧情
        /// </summary>
        Task = 2,
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 3,
        /// <summary>
        /// 无
        /// </summary>
        None = 4,
    }

} 

