
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    [System.Flags]
    public enum ChessDetailTag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 加速
        /// </summary>
        SpeedUp = 1,
        /// <summary>
        /// 刪除
        /// </summary>
        Delete = 2,
        /// <summary>
        /// 出售
        /// </summary>
        Sale = 3,
        /// <summary>
        /// 开启
        /// </summary>
        Open = 4,
        /// <summary>
        /// 撤回
        /// </summary>
        Redeem = 8,
        /// <summary>
        /// 删除气泡
        /// </summary>
        RemoveBubbly = 16,
        /// <summary>
        /// 购买气泡
        /// </summary>
        BuyBubbly = 32,
        /// <summary>
        /// 组合
        /// </summary>
        Combination = 64,
    }

} 

