
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum GuideType
    {
        /// <summary>
        /// 组件点击
        /// </summary>
        ComponentClick = 0,
        /// <summary>
        /// 对话
        /// </summary>
        Talk = 1,
        /// <summary>
        /// 棋子拖动
        /// </summary>
        ChessDrag = 2,
        /// <summary>
        /// 棋子点击
        /// </summary>
        ChessClick = 3,
        /// <summary>
        /// 订单完成
        /// </summary>
        OrderAchieve = 4,
        /// <summary>
        /// 订单高亮
        /// </summary>
        OrderFocus = 5,
        /// <summary>
        /// 订单详情
        /// </summary>
        OrderDetail = 6,
        /// <summary>
        /// 建筑页面按钮
        /// </summary>
        BuildComponentClick = 7,
        /// <summary>
        /// 棋子移动仓库
        /// </summary>
        ChessWareHouse = 8,
        /// <summary>
        /// 打开界面
        /// </summary>
        OpenView = 9,
    }

} 

