
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum GuideSaveKeyType
    {
        /// <summary>
        /// 不保存
        /// </summary>
        NoSave = 0,
        /// <summary>
        /// 触发保存
        /// </summary>
        ReachSave = 1,
        /// <summary>
        /// 完成保存
        /// </summary>
        AchieveSave = 2,
    }

} 

