
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum OrderType
    {
        /// <summary>
        /// 固定订单
        /// </summary>
        Fixed = 0,
        /// <summary>
        /// 随机订单
        /// </summary>
        Random = 1,
        /// <summary>
        /// 回收订单
        /// </summary>
        Recycle = 2,
        /// <summary>
        /// 活动订单
        /// </summary>
        Activity = 3,
    }

} 

