
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum OrderOpenEvent
    {
        /// <summary>
        /// 等级触发
        /// </summary>
        Level = 0,
        /// <summary>
        /// 生产器触发
        /// </summary>
        Producer = 1,
    }

} 

