
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum OrderGuideType
    {
        /// <summary>
        /// 生成特定订单ID
        /// </summary>
        SpawnSpecific = 0,
        /// <summary>
        /// 暂时没用
        /// </summary>
        SpawnGroup = 1,
        /// <summary>
        /// 暂时没用
        /// </summary>
        SpawnType = 2,
    }

} 

