
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ProducerEndType
    {
        /// <summary>
        /// 无效果
        /// </summary>
        None = 0,
        /// <summary>
        /// 降级
        /// </summary>
        LevelDown = 1,
        /// <summary>
        /// 消失
        /// </summary>
        Remove = 2,
    }

} 

