
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct RandomWeightItem
{
    public RandomWeightItem(ByteBuf _buf) 
    {
        Param = _buf.ReadInt();
        Weight = _buf.ReadInt();
    }

    public static RandomWeightItem DeserializeRandomWeightItem(ByteBuf _buf)
    {
        return new RandomWeightItem(_buf);
    }

    public readonly int Param;
    public readonly int Weight;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "param:" + Param + ","
        + "weight:" + Weight + ","
        + "}";
    }
}

}

