
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct Rewards
{
    public Rewards(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static Rewards DeserializeRewards(ByteBuf _buf)
    {
        return new Rewards(_buf);
    }

    public readonly int Id;
    public readonly int Count;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

