
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum SmallChessType
    {
        /// <summary>
        /// 普通棋子
        /// </summary>
        Product = 0,
        /// <summary>
        /// 生产器棋子
        /// </summary>
        Producer = 1,
        /// <summary>
        /// 自动生产
        /// </summary>
        AutoProducer = 2,
        /// <summary>
        /// 主棋盘货币
        /// </summary>
        MainCurrency = 3,
        /// <summary>
        /// 大门
        /// </summary>
        Gate = 4,
    }

} 

