
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private Chess_Config m_Chess_Config;
    public Chess_Config ChessConfig 
    {
        get
        {
            if (m_Chess_Config == null)
            {
                m_Chess_Config = new Chess_Config(defaultLoader("chess_config"));
                m_Chess_Config.ResolveRef(this);
            }
            return m_Chess_Config;
        }
        set
        {
            m_Chess_Config = value;
            m_Chess_Config.ResolveRef(this);
        }
    }
    private Chess_Group m_Chess_Group;
    public Chess_Group ChessGroup 
    {
        get
        {
            if (m_Chess_Group == null)
            {
                m_Chess_Group = new Chess_Group(defaultLoader("chess_group"));
                m_Chess_Group.ResolveRef(this);
            }
            return m_Chess_Group;
        }
        set
        {
            m_Chess_Group = value;
            m_Chess_Group.ResolveRef(this);
        }
    }
    private Chess_Initial m_Chess_Initial;
    public Chess_Initial ChessInitial 
    {
        get
        {
            if (m_Chess_Initial == null)
            {
                m_Chess_Initial = new Chess_Initial(defaultLoader("chess_initial"));
                m_Chess_Initial.ResolveRef(this);
            }
            return m_Chess_Initial;
        }
        set
        {
            m_Chess_Initial = value;
            m_Chess_Initial.ResolveRef(this);
        }
    }
    private Chess_Tag m_Chess_Tag;
    public Chess_Tag ChessTag 
    {
        get
        {
            if (m_Chess_Tag == null)
            {
                m_Chess_Tag = new Chess_Tag(defaultLoader("chess_tag"));
                m_Chess_Tag.ResolveRef(this);
            }
            return m_Chess_Tag;
        }
        set
        {
            m_Chess_Tag = value;
            m_Chess_Tag.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
