
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum TopRewardType
    {
        /// <summary>
        /// 常规棋子
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 奖励宝箱
        /// </summary>
        SpecialTreasure = 1,
        /// <summary>
        /// 通行证宝箱
        /// </summary>
        PassportTreasure = 2,
        /// <summary>
        /// 活动点数
        /// </summary>
        ActivityPoint = 3,
        /// <summary>
        /// 特殊buff
        /// </summary>
        ChessboardBuff = 4,
        /// <summary>
        /// 活动道具
        /// </summary>
        ActivityProp = 5,
    }

} 

